baseURL = "https://example.com"
languageCode = "zh-CN"
title = "阿 君、的博客"     #网站名称
theme = "LeaveIt"      #当前使用的主题名称，与themes文件夹中的子文件夹名称一致

paginate = 12                   # 每页显示的博文数量
enableEmoji = true              # 允许使用 Emoji 表情，建议 true
enableRobotsTXT = true          # 允许爬虫抓取到搜索引擎，建议 true
googleAnalytics = ""            # 谷歌统计

preserveTaxonomyNames = true    

[blackfriday]
  hrefTargetBlank = true
  nofollowLinks = true
  noreferrerLinks = true

[Permalinks]
 posts = "/:year/:filename/"

[menu]
  [[menu.main]]
    name = "博客"
    url = "/posts/"
    weight = 1

  [[menu.main]]
    name = "分类"
    url = "/categories/"
    weight = 2

  [[menu.main]]
    name = "标签"
    url = "/tags/"
    weight = 3

  [[menu.main]]
    name = "关于"
    url = "/about/"
    weight = 4

[params]
    since = 2020
    author = "阿 君 、"                           # Author's name
    avatar = "/images/me/me.JPG"           # Author's avatar
    subtitle = "明日安在、无人能允"         # Subtitle
    cdn_url = ""           # Base CDN URL
    home_mode = "" # post or other

    google_verification = ""
   
    description = "" # site description
    keywords = "" # site keywords

    beian = ""
    baiduAnalytics = ""

    license= ''

[params.social]
    GitHub = "/Mr-ZhangJun"
    Email  = "mr.ajun@foxmail.com"
    Wechat = "/static/images/me/Wechat.jpeg"

